TEST_CENTERS = [
        "Alkmaar (Olympiaweg 28)",
        "Almelo (Bedrijvenpark Twente 305)",
        "Amsterdam (Naritaweg 150)",
        "Apeldoorn (Antillen 11)",
        "Arnhem (Hazenkamp 10)",
        "Assen (Azieweg 25a)",
        "Assen (Overcingellaan 13)",
        "Barendrecht (Zwaalweg 1)",
        "Bergen Op Zoom (Gagelboslaan 162)",
        "Berkel-Enschot (Bosscheweg 11)",
        "Breda (Heerbaan 4)",
        "Den Bosch (Hambakenwetering 13A)",
        "Den Helder (Nijverheidsweg 8c)",
        "Deventer (Duisburgstraat 10)",
        "Doetinchem (Koopmanslaan 3)",
        "Dordrecht (Egstraat 4)",
        "Eemnes (Bramenberg 6)",
        "Eindhoven (Hoevenweg 20)",
        "Emmeloord (Boslaan 30)",
        "Emmen (Nijbracht 112)",
        "Enschede (Burgemeester Stroinkstraat 300)",
        "Goes (M.A. de Ruijterlaan 2)",
        "Gouda (Zwolleweg 10)",
        "Groningen (Protonstraat 3)",
        "Haarlem (Professor Eijkmanlaan 2-4)",
        "Harderwijk (Tesselschadelaan 1)",
        "Heerenveen (Businesspark Friesland-West 41)",
        "Hoogeveen (Grote Beer 20)",
        "Hoorn Nh (Holenweg 14G)",
        "Kerkrade (Spekhofstraat 24)",
        "Leeuwarden (Douwe Tammingawei 30)",
        "Leiden (Smaragdlaan 99A)",
        "Leusden (Fokkerstraat 21)",
        "Maastricht (Stadionplein 34)",
        "Meppel (Blankenstein 230)",
        "Mierlo (Geldropseweg 10)",
        "Nijmegen (Wijchenseweg 2)",
        "Rijswijk Zh (Lange Kleiweg 30)",
        "Roermond (Oude Trambaan 27)",
        "Roosendaal (De Stok 12)",
        "Rotterdam (Noorderbocht 25)",
        "Schelluinen (Sportlaan 2A)",
        "Sneek (Smidsstraat 6)",
        "Spijkenisse (Curieweg 19)",
        "Terneuzen (Handelspoort 3A)",
        "Tiel (Stephensonstraat 25A)",
        "Urmond (Mauritslaan 49)",
        "Utrecht (Mississippidreef 151)",
        "Venlo-Blerick (Antoniusplein 2)",
        "Vlissingen (Marie Curieweg 5)",
        "Weert (Risseweg 46)",
        "Winschoten (Zeefbaan 20A)",
        "Zaandam (Kuilpad 1)",
        "Zoetermeer (Zilverstraat 40)",
        "Zwolle (Branderweg 15)"
]
