# Generated by Django 3.2.3 on 2021-06-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('candidate_number', models.CharField(max_length=100, unique=True)),
                ('birth_date', models.DateField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('test_type', models.CharField(max_length=30)),
                ('desired_date', models.DateField()),
                ('days_to_skip', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
