# Generated by Django 3.2.3 on 2021-06-17 23:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='automatic_booking',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='info_validation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_crawled',
        ),
        migrations.AddField(
            model_name='student',
            name='info_validation',
            field=models.CharField(choices=[('unchecked', 'unchecked'), ('valid', 'valid'), ('invalid', 'invalid')], default='unchecked', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='last_crawled',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
