# Generated by Django 3.2.3 on 2021-07-02 00:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210702_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gov_password',
            field=models.CharField(default='random', max_length=150, validators=[django.core.validators.MinLengthValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gov_username',
            field=models.CharField(default='random', max_length=50, validators=[django.core.validators.MinLengthValidator(1)]),
            preserve_default=False,
        ),
    ]
