# Generated by Django 3.2.3 on 2021-07-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210704_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student_limit',
            field=models.IntegerField(blank=True, default=100),
        ),
    ]
