# Generated by Django 3.2.3 on 2021-07-09 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_profile_student_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('use_count', models.IntegerField(blank=True, default=0)),
                ('ban_count', models.IntegerField(blank=True, default=0)),
                ('is_banned', models.BooleanField(blank=True, default=False)),
                ('last_used', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='last_crawled',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
