# Generated by Django 3.2.3 on 2021-07-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_proxy_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[(1, 'In analysis'), (2, 'Invalid'), (3, 'Searching'), (4, 'Test found')], default='unchecked', max_length=20),
        ),
    ]
