# Generated by Django 3.2.3 on 2021-07-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210709_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('1', 'In analysis'), ('2', 'Invalid'), ('3', 'Searching'), ('4', 'Test found'), ('5', 'Paused')], default='1', max_length=20),
        ),
    ]
