# Generated by Django 3.2.3 on 2021-07-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('1', 'Deactivated'), ('2', 'Activated'), ('3', 'Invalid')], default='1', max_length=20),
        ),
    ]
