# Generated by Django 3.2.3 on 2021-07-23 23:17

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='earliest_test_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='test_centers',
        ),
        migrations.AddField(
            model_name='student',
            name='test_center',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='api.testcenter'),
        ),
        migrations.AddField(
            model_name='student',
            name='time_range',
            field=models.CharField(choices=[('1', '1 week'), ('2', '2 weeks'), ('3', '3 weeks'), ('4', '4 weeks'), ('5', '5 weeks'), ('6', '6 weeks'), ('7', '7 weeks'), ('8', '8 weeks')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='token',
            name='expiration',
            field=models.DateTimeField(blank=True, default=api.models.get_expiration_time),
        ),
    ]
