# Generated by Django 3.2.3 on 2021-07-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_student_test_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='time_range',
            field=models.CharField(choices=[('1', '2 weeks'), ('2', '4 weeks'), ('3', '8 weeks')], default='1', max_length=20),
        ),
    ]
