# Generated by Django 3.2.3 on 2021-07-25 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_student_time_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='test_center',
        ),
        migrations.RemoveField(
            model_name='student',
            name='time_range',
        ),
        migrations.AddField(
            model_name='student',
            name='earliest_test_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='test_centers',
            field=models.ManyToManyField(blank=True, to='api.TestCenter'),
        ),
    ]
