# Generated by Django 3.2.3 on 2021-07-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210725_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('1', 'In analysis'), ('2', 'Invalid'), ('3', 'Searching'), ('4', 'Test found'), ('5', 'Paused')], default='3', max_length=20),
        ),
    ]
