# Generated by Django 3.2.3 on 2021-07-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_student_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='earliest_test_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='test_centers',
        ),
        migrations.AddField(
            model_name='student',
            name='date_range',
            field=models.CharField(choices=[('1', '2 weeks'), ('2', '4 weeks'), ('3', '12 weeks')], default='1', max_length=20),
        ),
    ]
