# Generated by Django 3.2.3 on 2021-07-28 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210728_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='date_range',
            new_name='search_range',
        ),
    ]
