# Generated by Django 3.2.3 on 2021-07-28 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_date_range_student_search_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='test_center',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='api.testcenter'),
            preserve_default=False,
        ),
    ]
