# Generated by Django 3.2.3 on 2021-07-29 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_profile_test_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateFound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('week_day', models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=30)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('free_slots', models.IntegerField()),
                ('found_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.profile')),
                ('test_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dates', to='api.testcenter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
