# Generated by Django 3.2.3 on 2021-07-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_datefound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datefound',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='datefound',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
