# Generated by Django 3.2.3 on 2021-07-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20210729_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='search_range',
            field=models.CharField(choices=[('2', '2 weeks'), ('4', '4 weeks'), ('12', '12 weeks')], default='1', max_length=20),
        ),
    ]
