# Generated by Django 3.2.3 on 2021-07-31 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20210730_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='last_crawled',
        ),
    ]
