# Generated by Django 3.2.3 on 2021-07-31 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_profile_searches'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='test_booked',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
