# Generated by Django 3.2.3 on 2021-08-03 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_student_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='driving_school_name',
            field=models.CharField(default='hey', max_length=150, validators=[django.core.validators.MinLengthValidator(1)]),
            preserve_default=False,
        ),
    ]
