# Generated by Django 3.2.3 on 2021-08-03 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_profile_driving_school_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='test_type',
        ),
    ]
