# Generated by Django 3.2.3 on 2021-08-05 14:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_datefound_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_crawled',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
