# Generated by Django 3.2.3 on 2021-09-07 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_crawlerinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerinstance',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='crawler_instance', to='api.profile'),
            preserve_default=False,
        ),
    ]
