# Generated by Django 3.2.3 on 2021-09-07 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_crawlerinstance_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlerinstance',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawler_instance', to=settings.AUTH_USER_MODEL),
        ),
    ]
